### PR TITLE
workflow package registry

### LINKED ISSUE #151: Change automated build to publish module-jars in github maven package registry
We might want to change our automated builds so that the all module-jars are published to the project's github maven package registry. This could also apply to the SNAPSHOTS builds.

### PR DESCRIPTION
**Pull request by wetret**
closes #151

### CODE REVIEW

**Comment by wetret** [comment]
@hhund Maybe you can remove the packages that were already created during testing of the workflow. I don't have the rights to do it.

**Comment by hhund** [comment]
If I understand the [documentation](https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/deleting-a-package#about-public-package-deletion) correctly public packages can't be deleted.

Can you add some info to the [README.md](https://github.com/highmed/highmed-dsf/blob/issues/151_workflow_package_registry/README.md) file on how to use the packages? Maybe with links to the GitHub documentation.

I do like the fact, that the publish actions are only executed on the master and develop branches. To make sure we only publish new release (not SNAPSHOT) if we intend to, maybe we should make the master branch publish action manually triggered. Maybe using `workflow_dispatch`: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/ or something like described here: https://levelup.gitconnected.com/how-to-manually-trigger-a-github-actions-workflow-4712542f1960

**Comment by wetret** [comment]
I added a section to the wiki about the GitHub Maven Package Registry:
[https://github.com/highmed/highmed-dsf/wiki/Using-the-Github-Maven-Package-Registry](https://github.com/highmed/highmed-dsf/wiki/Using-the-Github-Maven-Package-Registry)

**Comment by wetret** [comment]
I changed the workflow to be triggered on closed pull requests or if a release is published. The workflow should not be triggered if a a release draft is created.

**Review by hhund — APPROVED** [review]
I removed the redundant `snapshotRespository` tag from the parent pom in b701024
and will merge now.

**Pull request merged**
